### ISSUE TITLE
Crash during game startup

### ISSUE THREAD

**Issue by border999** [TheidenHD/TiCon-Addons#4]
Just switched over from the original version of this mod to your version. Crashed while the game was still loading.
https://gist.github.com/border999/5df6281092aff80d769694e9eb838904

**Comment by SonicX8000** [comment]
Can confirm that "Tinkers'+Addons-1.12.2-1.0.9" crashes at start-up.

Crash:
https://pastebin.com/40d1mCXC

**Comment by TheidenHD** [comment]
Compiler messed up, should work now.
